name: Deploy Azure WebApp with Terraform

on:
  push:
    branches:
      - feature_rel1

env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

     

      - name: Terraform Init
        working-directory: ./terraform  # Change this path to the location of your Terraform directory
        run: terraform init

      - name: Remove existing lock file
        run: rm -f .terraform.lock.hcl

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform  # Change this path to the location of your Terraform directory
        run: |
          PLAN_NAME="tfplan-${GITHUB_RUN_ID}"
          terraform plan -out=$PLAN_NAME

      - name: Save Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ./terraform/$PLAN_NAME

  manual-approval:
    name: Manual Approval for Apply
    runs-on: ubuntu-latest
    needs: terraform
    environment: dev  # Name of the GitHub environment requiring approval
    steps:
      - name: Wait for Approval
        run: echo "Waiting for manual approval before applying Terraform changes."

  apply:
    name: Apply Terraform Plan
    runs-on: ubuntu-latest
    needs: manual-approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve tfplan


  