name: Deploy Azure WebApp with Terraform

on:
  push:
    branches:
      - feature_rel1

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
     name: Terraform Deployment
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        working-directory: ./terraform  # Change this path to the location of your Terraform directory
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate
  
      - name: Plan Terraform
        working-directory: ./terraform
        run: terraform plan
      

  manual-approval:
    name: Manual Approval for Apply
    runs-on: ubuntu-latest
    needs: terraform
    environment: dev
    steps:
      - name: Wait for Approval
        run: echo "Waiting for manual approval before applying Terraform changes."

  apply:
    name: Apply Terraform Plan
    runs-on: ubuntu-latest
    needs: manual-approval
     
    steps:
       - name: Apply Terraform
         working-directory: ./terraform
         run: terraform apply -auto-approve
    