name: Deploy Azure WebApp with Terraform

on:
  push:
    branches:
      - feature_rel1

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}


    - name: Initialize Terraform
      working-directory: ./terraform 
      run: terraform init

    - name: Validate Terraform
      working-directory: ./terraform 
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./terraform 
      run: terraform plan

   # - name: Apply Terraform
  # working-directory: ./terraform 
   #   run: terraform apply -auto-approve
