name: Deploy Azure WebApp with Terraform

on:
  push:
    branches:
      - feature_rel1

jobs:
  terraform:
    name: Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      

     


      - name: Terraform Init
        working-directory: ./terraform  # Change this path to the location of your Terraform directory
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        working-directory: ./terraform  # Change this path to the location of your Terraform directory
        run: terraform plan

     # - name: Terraform Apply
     #   working-directory: ./terraform  # Change this path to the location of your Terraform directory
     #   run: terraform apply -auto-approve

     